theme="solarized"

[editor]
rulers = [101]
idle-timeout = 0
line-number = "relative"

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal.space]
"%" = "file_picker_in_current_buffer_directory"
