[language-server.clangd]
command = "clangd"
args = ["-header-insertion=never"]

[[language]]
name = "c"
indent = { tab-width = 8, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 8, unit = "\t" }
